cabal-version: 3.0
name:          l1ne
version:       0.1.0.0
license:       NONE
author:        c0utin
maintainer:    rafaelcouto111@gmail.com
build-type:    Simple

common warnings
    ghc-options: -Wall


executable l1ne
    import:           warnings
    main-is:          Main.hs
    other-modules:    Cli
    hs-source-dirs:   src/l1ne
    build-depends:    base ^>=4.18.3.0
    default-language: GHC2021
